######################################################################
# Automatically generated by qmake (3.0) Sun Apr 19 13:03:16 2015
######################################################################

TEMPLATE = app
TARGET = Hyperbole_qt
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    drawWidget.cpp \
    hyper.cpp \
    inputsWidget.cpp
SOURCES +=
HEADERS += \
    drawWidget.h \
    hyper.h \
    inputsWidget.h
QT += widgets
