######################################################################
# Automatically generated by qmake (3.0) Sun Apr 19 13:03:16 2015
######################################################################

TEMPLATE = app
TARGET = Hyperbole_qt
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    hyper.c \
    drawWidget.cpp
SOURCES +=
HEADERS += \
    hyper.h \
    drawWidget.h
QT += widgets
